cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'

brew 'ack'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'libcaca'
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'puma/puma/puma-dev'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'
brew 'zsh-completions'
brew 'watch'
brew 'yarn'
brew 'telnet'
brew 'watchman'
brew 'htop'
brew 'gpg'
brew 'tig'

cask '1password'
cask 'adium'
cask 'firefox'
cask 'handbrake'
cask 'seashore'
cask 'steam'
cask 'transmission'
cask 'tunnelbear'
cask 'vlc'
